name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npx webpack --config ./webpack.config.npm.js
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
